#!/usr/bin/env python3
"""
Example usage of the YouTube Downloader
"""

def show_examples():
    print("# YouTube Video Downloader - Examples")
    print()
    print("## Features")
    print("- Download YouTube videos in MP4 format")
    print("- Extract audio from videos as MP3 files")
    print("- Download audio only (as MP3)")
    print("- Choose video quality (highest, lowest, or specific resolution)")
    print()
    print("## Installation")
    print("The required packages are already installed:")
    print("```bash")
    print("pip install pytube moviepy==1.0.3")
    print("```")
    print()
    print("## Usage Examples")
    print()
    print("### Download Video Only (MP4)")
    print("```bash")
    print("python youtube_downloader.py [YOUTUBE_URL] --video")
    print("```")
    print()
    print("### Download Audio Only (MP3)")
    print("```bash")
    print("python youtube_downloader.py [YOUTUBE_URL] --audio")
    print("```")
    print()
    print("### Download Both Video and Audio")
    print("```bash")
    print("python youtube_downloader.py [YOUTUBE_URL] --both")
    print("```")
    print()
    print("### Specify Video Quality")
    print("```bash")
    print("# Highest quality (default)")
    print("python youtube_downloader.py [YOUTUBE_URL] --video --quality highest")
    print()
    print("# Lowest quality")
    print("python youtube_downloader.py [YOUTUBE_URL] --video --quality lowest")
    print()
    print("# Specific resolution")
    print("python youtube_downloader.py [YOUTUBE_URL] --video --quality 720p")
    print("```")
    print()
    print("### Specify Output Directory")
    print("```bash")
    print("python youtube_downloader.py [YOUTUBE_URL] --video --output ./my_videos")
    print("```")
    print()
    print("### Complete Example")
    print("```bash")
    print("# Download a video in highest quality and extract audio")
    print("python youtube_downloader.py https://www.youtube.com/watch?v=dQw4w9WgXcQ --both")
    print("```")
    print()
    print("Note: Always respect copyright laws and YouTube's Terms of Service when using this tool.")

if __name__ == "__main__":
    show_examples()